accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
]

books/urls.py
from django.conf.urls import url
from . import views

app_name = 'books'

urlpatterns = [
    url(r'^$', views.BookSearchView.as_view(), name='search'),
    url(r'^(?P<pk>\d{9}[\d|X])/', views.BookView.as_view(), name='detail'),

]

common/urls.py
from django.conf.urls import url
from . import views

app_name = 'common'

urlpatterns = [
    url(r'^$', views.HomePageView.as_view(), name='index'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
]

orders/urls.py
from django.conf.urls import url
from . import views

app_name = 'orders'

urlpatterns = [
    url(r'^$', views.OrderListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/', views.OrderDetailView.as_view(), name='detail'),
    url(r'^create/$', views.OrderCreateView.as_view(), name='create'),
    url(r'^confirm/$', views.OrderConfirmView.as_view(), name='confirm'),
]

webapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^books/', include('books.urls')),
    url(r'^orders/', include('orders.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^', include('common.urls')), # has to be last because this matches anything
]

common/models.py
from django.db import models

# Create your models here.

common/views.py
from django.shortcuts import render
from django.views import generic

# Create your views here.

class HomePageView(generic.TemplateView):
    template_name = 'common/homepage.html'

class AboutView(generic.TemplateView):
    template_name = 'common/about.html'

templates/common/about.html
{% extends 'common/base.html' %}

{% block title %}About Us{% endblock %}

{% block content %}

<h1>This is the about page.</h1>

{% endblock %}

templates/common/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}ISBN Search{% endblock %}</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
        crossorigin="anonymous">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp"
        crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>

    <style>
    #logo {
        max-width: 100px;
    }

    .navbar {
        background: #1F1F1F;
    }

    .navbar-nav li a {
        padding-top: 40px;
        padding-bottom: 40px;
    }
    {% block style %}
    {% endblock %}
    </style>

    <script>
    {% block script %}
    {% endblock %}
    </script>
</head>

<body>
    {% include "common/navbar.html" %}
    <div class="container">

    {% block content %}
    {% endblock %}

    </div>
</body>

</html>

templates/common/homepage.html
{% extends 'common/base.html' %}

{% block title %}WebApp{% endblock %}

{% block content %}

<h1>This is the homepage.</h1>

{% endblock %}

templates/common/navbar.html
{% load staticfiles %}

<nav class="navbar navbar-inverse">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
                aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
            <a class="navbar-left" href="{% url 'common:index' %}"><img id="logo" src="{% static 'common/img/logo.jpg' %}" alt="AppLogo"></a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-left">
                <li><a href="{% url 'books:search' %}">Search</a></li>

            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'common:about' %}">About</a></li>

                {% include "common/navbar_login.html" %}

            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

templates/common/navbar_login.html
{% if user.is_authenticated %}

<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.name }}<span class="caret"></span></a>
    <ul class="dropdown-menu">
        <li><a href="{% url 'orders:list' %}">Orders</a></li>
        <li role="separator" class="divider"></li>
        <li><a href="#">Settings</a></li>
    </ul>
</li>
<li><a href="{% url 'accounts:logout' %}">Logout</a></li>

{% else %}

<li><a href="{% url 'accounts:login' %}">Login</a></li>

{% endif %}